### ISSUE TITLE
not able to install it

### ISSUE THREAD

**Issue by praveshkhatana** [armackey/nativescript-twilio-video#1]

**Comment by armackey** [comment]
Hi @praveshkhatana, 

Mind explaining the error or the steps you've done to produce this issue so I can replicate it?

**Comment by praveshkhatana** [comment]
I was trying to add it through "tns plugin add nativescript-twilio-video"
command but now I am Okay and added from zip file.

Could you please provide some quick demo sample code for nativescript
angular typescript.

**Comment by armackey** [comment]
Maybe sometime in the future.

Gonna close this.

**Comment by cerireyhan** [comment]
@praveshkhatana Were you able to use this plugin with nativescript angular?
@armackey I am using angular and getting the error below when I try to connect to room with my twilio room id. Do you have any suggestions? I would like to make an angular-demo app if this is solved. Thanks in advance.

`JS: ERROR Error: Uncaught (in promise): TypeError: (intermediate value).build is not a function
JS: TypeError: (intermediate value).build is not a function
JS:     at VideoActivity.requestAudioFocus (file:///data/data/com.teleclinic.medacardoctorapp/files/app/tns_modules/nativescript-twilio-video/src/android/twilio-video.js:339:16)
JS:     at VideoActivity.configure_audio (file:///data/data/com.teleclinic.medacardoctorapp/files/app/tns_modules/nativescript-twilio-video/src/android/twilio-video.js:315:18)
JS:     at VideoActivity.connect_to_room (file:///data/data/com.teleclinic.medacardoctorapp/files/app/tns_modules/nativescript-twilio-video/src/android/twilio-video.js:43:18)
`

_And I got the error below if I disable the audio option in connect_to_room._

`S: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.twilio.video.LocalVideoTrack.isReleased()' on a null object reference
JS:     com.twilio.video.ConnectOptions.checkVideoTracksReleased(ConnectOptions.java:57)
JS:     com.twilio.video.ConnectOptions$Builder.build(ConnectOptions.java:361)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:789)
JS:     android.os.Handler.dispatchMessage(Handler.java:98)
JS:     android.os.Looper.loop(Looper.java:251)
JS:     android.app.ActivityThread.main(ActivityThread.java:6589)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Comment by armackey** [comment]
@cerireyhan 

Hey 
I don't use angular with NS so I can't give much directions on that. I just updated the plugin removing most of the requestAudioFocus that I believe is causing the error. Please download the latest version and let me know if you're still seeing an issue with Android.

**Comment by armackey** [comment]
Also, if you'd like to make a pull request with Angular, that's totally fine!

**Comment by cerireyhan** [comment]
@armackey thanks for the quick reply!

Your update solved my audio focus issue but I'm still getting the error below related to video. I can connect the room successfully if I disable video. I'll look into it but I'll appreciate your help :) 

`ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.twilio.video.LocalVideoTrack.isReleased()' on a null object reference
JS:     com.twilio.video.ConnectOptions.checkVideoTracksReleased(ConnectOptions.java:92)
JS:     com.twilio.video.ConnectOptions$Builder.build(ConnectOptions.java:396)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:173)
JS:     android.app.ActivityThread.main(ActivityThread.java:6459)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
`

**Comment by armackey** [comment]
@praveshkhatana 
Here's an angular example.
https://github.com/armackey/nativescript-twilio-video/tree/master/demo-ng
Good luck.
