### ISSUE TITLE
NativeScript 6 support

### ISSUE THREAD

**Issue by Izrab** [armackey/nativescript-twilio-video#11]
Add support for NativeScript version 6 and make it have the NS6 confirmed **badge** on market.nativescript.org 
![imgonline-com-ua-twotoone-CpdKwEu1OwbnKxb](https://user-images.githubusercontent.com/22328131/61965774-ea6c7b80-af85-11e9-9599-bcd2239799d2.jpg)

**Comment by armackey** [comment]
Good suggestion. Will work on this.

**Comment by armackey** [comment]
added support. waiting for market place to update then will close.

**Comment by Izrab** [comment]
![image](https://user-images.githubusercontent.com/22328131/62003114-9917d580-b0c6-11e9-8424-885714e376c5.png)

**Comment by Izrab** [comment]
@armackey , works good on both Android (version 9) and iOS. Unlike some other plugins, yours does not crash when I resume app or exit and reopen, also unlike some other plugins, yours does not stretch camera or views. 
Thanks.
