### ISSUE TITLE
Switch camera option

### ISSUE THREAD

**Issue by Izrab** [armackey/nativescript-twilio-video#13]
How do I make a button, and when user tapped on the button, it switches the camera, from rear to front camera, and vice versa.
Using NS 6 and twilio plugin version 1.1.6

**Comment by armackey** [comment]
This should work. 

`this.videoActivity.toggle_local_video();`

**Comment by Izrab** [comment]
This does not work.
I see local video, but does not switch.

**Comment by Izrab** [comment]
It did not work. If I tap on switch button, the local video immediately becomes black.

**Comment by armackey** [comment]
This is a feature request. Will do this at a later date.

https://github.com/armackey/nativescript-twilio-video/issues/14
