### ISSUE TITLE
Is this plugin operational?

### ISSUE THREAD

**Issue by paologrimaldi** [armackey/nativescript-twilio-video#18]
I saw a last commit 8 months ago and a sad face as the last open issue, what is the status? Is there any other plugin out there for twilio video and nativescript integration?

Regards

**Comment by Prashanth-Mani** [comment]
Are there any updates on this ticket? we can't use this plugin on the latest NativeScript version

**Comment by armackey** [comment]
Sorry! 

I stopped supporting this project a very long time ago.

**Comment by Prashanth-Mani** [comment]
Thanks for the updates,@armacky

Is there any alternative plugin available for this **native script-twilio-video** plugin?
I tried a couple of plugins, but didn't help

**Comment by armackey** [comment]
@Prashanth-Mani 

You could try https://www.npmjs.com/package/nativescript-webrtc-plugin but the last update was 4 years ago. Your best bet is another framework that has continued support unfortunately. Like react native.
