### ISSUE TITLE
Not receiving remote video feed of Android on IOS

### ISSUE THREAD

**Issue by praveshkhatana** [armackey/nativescript-twilio-video#5]
Its working fine with 2 IOS devices but, I am not getting remote feed of android on IOS side. Just showing black screen on IOS.

**Comment by armackey** [comment]
Hmm.. Haven't looked at this in awhile. I may have some time over the weekend to help out.

**Comment by praveshkhatana** [comment]
thanks @armackey

**Comment by praveshkhatana** [comment]
Actual issue is on Android side..tried with 2 android devices this time and it didn't work. black remote screen on both sides.
Only IOS is working.

**Comment by praveshkhatana** [comment]
Hey @armackey 
Did you find the issue?

**Comment by praveshkhatana** [comment]
@armackey ready to pay for this android fix.. need it urgently. let me know you email id so we can talk about it

**Comment by armackey** [comment]
@praveshkhatana alrighty.. no need to pay. I'm done with work in 3 hours. From there I need a couple hours re-familiarizing myself with the code and I should have a fix tonight. I should have an update for you in about 8 hours.

**Comment by armackey** [comment]
@praveshkhatana Is it working android to android?

**Comment by praveshkhatana** [comment]
@armackey nope, it's neither working android to android nor ios to android.

> @praveshkhatana Is it working android to android?

**Comment by armackey** [comment]
> @armackey nope, it's neither working android to android nor ios to android.
> 
> > @praveshkhatana Is it working android to android?

@praveshkhatana okay, thank you.

**Comment by armackey** [comment]
pull the latest and greatest and it should work just fine now.
closing.
